language: node_js
node_js:
  - "0.10"
addons:
  sauce_connect: true
env:
  global:
    # Sauce Connect credentials
    - secure: DCRo6VuiNTbdfv6aS3Ak8yN5rxZKnV8licKKqrgZxl74X4IfvrYYOh9vHASZIrn/HwaPrc19Yv8mt7caDd0ehru+bpgIRcwGgLdPiWB2QNKEJZ7Rjn61L3XaBuiArsQfpdd1j2s9cbMiDYAEHIU1qmPL7F5OsYqwwLP4guI5waY=
    - secure: KFDnudRwAuxI6pGv1wYf0/FhtzXS8cCm1AEpujAFeB/taMoL1eDzHTGo8oBfaXgd9YLm4u5p/L+mlCIIlhkBRvjc92N6hYy443wX9i6LXSPqxS/Dp6GsoTQWg2mxyFSTxI4pb9KK12TtVGlpmu0BhEYtWjGmuCBmct4Cxc5E38c=
script: "npm run travis"
